# Generated by Django 4.2.7 on 2023-11-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='slug',
            field=models.SlugField(blank=True, max_length=320),
        ),
        migrations.AlterField(
            model_name='images',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='images',
            name='url',
            field=models.URLField(max_length=320),
        ),
    ]
